name: CI

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ubuntu-latest, windows-latest]
        e2e-browser: ['chromium']
        include:
          - node-version: 16
            os: ubuntu-latest
            e2e-browser: 'firefox'
          - node-version: 16
            os: macOS-latest
            e2e-browser: 'webkit'
          - node-version: 18
            os: ubuntu-latest
            e2e-browser: 'chromium'
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install --frozen-lockfile
      - run: npm test
